apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobsters
  labels:
    app: lobsters
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lobsters
  template:
    metadata:
      labels:
        app: lobsters
    spec:
      containers:
      - name: lobsters
        image: "kelseyhightower/lobsters:2.0.0"
        env:
          - name: DATABASE_URL
            value: "mysql2://root:password@mysql.default.svc.cluster.local:3306/lobsters"
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
