apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6.32
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-store
                key: mysql-root-pass
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-store
                key: mysql-pass
          - name: MYSQL_USER
            value: scott
          - name: MYSQL_DATABASE
            value: lobsters
        ports:
         - name: mysql
           containerPort: 3306
        volumeMounts:
          - name: mysql
            mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql-claim
